from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate
import json

class SummaryTagsAgent:
    def __init__(self, blog_title, blog_content):
        self.blog_title = blog_title
        self.blog_content = blog_content

        # Defining LLM to be used by planner and reviewer agent
        self.llm = ChatOllama(
            model = "smollm:1.7b",
            temperature = 0,
            seed = 45,
            format = "json"
            )
    
        self.llm_finalizer = ChatOllama(
            model = "llama3.2:latest",
            temperature = 0,
            seed = 12,
            verbose = True,
            format = "json"
        )
                
    def plannerAgent(self):
        """ The planner agents generates tags and summary for a given blog title and content."""

        # Prompt template
        planner_prompt_template = """
You are a helpful assistant. Please follow ALL the instructions given below.
1. Generate EXACTLY THREE topical tags based on blog_title and blog_content. The three tags should be different from each other. 
2. Generate a one-sentence summary of blog_content in <= 25 words. You are strictly PROHIBITED from using blog_title for generating summary. The summary should be meaningful and cover all aspects of the blog_content.
3. Output valid JSON with exactly two keys: "summary" and "tags". No extra keys, no extra text.

blog_title: {blog_title}
blog_content: {blog_content}

"""
        # Creating Planner Agent LLM chain
        planner_prompt = ChatPromptTemplate.from_template(planner_prompt_template)
        planner_llm_chain = planner_prompt | self.llm
        planner_output = planner_llm_chain.invoke({"blog_title":self.blog_title, "blog_content":self.blog_content})
        # extracting JSON from output 
        planner_response = planner_output.content

        # Extracting JSON from string
        planner_response = json.loads(planner_response)

        # Extracting summary and tags
        summary = planner_response["summary"]
        tags = planner_response["tags"]

        return tags, summary
    
    def reviewerAgent(self, tags, summary):
        """ The reviewer agent reviews the summary and tags generated by planner agent"""
        #Prompt template
        reviewer_prompt_template = """
        You are an instruction-following model. 
Your ONLY task is to update the summary and tags according to strict rules.

Follow these rules EXACTLY:

RULES FOR SUMMARY:
- If the provided summary has 25 words or fewer, use it unchanged.
- If it has more than 25 words, generate a NEW one-sentence summary using ONLY the blog_content.
- The final summary MUST be 25 words or fewer.

RULES FOR TAGS:
- If the provided tags list contains EXACTLY 3 tags, use them unchanged.
- If it contains any number other than 3, generate EXACTLY 3 new topical tags using blog_content and blog_title.
- Tags must be single words or short phrases (no sentences).

OUTPUT FORMAT (MANDATORY):
- Output ONLY valid JSON.
- JSON must contain EXACTLY these two keys:
  "updated_summary"
  "updated_tags"
- No explanations, no extra text, no commentary.

INPUT:
summary: {summary}
tags: {tags}
blog_title: {blog_title}
blog_content: {blog_content}

Now produce the JSON output.
"""
       
        # Reviewer LLM chain
        reviewer_prompt = ChatPromptTemplate.from_template(reviewer_prompt_template)
        reviewer_llm_chain = reviewer_prompt | self.llm
        reviewer_output = reviewer_llm_chain.invoke({"summary":summary, "tags":tags, "blog_title":self.blog_title, "blog_content":self.blog_content})

        # extracting JSON from output
        reviewer_response  = reviewer_output.content

        # Extracting JSON from string
        reviewer_response = json.loads(reviewer_response)

        return reviewer_response["updated_tags"], reviewer_response["updated_summary"]
    
    def finalizer(self, tags, summary):
        """The finalizer generates the final cleaned tags and summary for the given blog title and content."""

        finalizer_prompt_template = """You are an instruction-following model. 
Your ONLY task is to CLEAN the tags and summary according to strict rules.

Follow these rules EXACTLY:

TAG CLEANING RULES:
- Replace every underscore (_) with a space in the tags.
- Do not change anything else.

SUMMARY CLEANING RULES:
- If the provided summary has no special characters apart from space, hyphen, period, comma and semicolon, use it UNCHANGED.
- If it has any other special characters, remove them.
- DO NOT change the wording of the summary, except for removing invalid special characters.

OUTPUT FORMAT (MANDATORY):
- Output ONLY valid JSON.
- JSON must contain EXACTLY these two keys:
  "tags"
  "summary"
- No explanations, no extra text, no commentary.

INPUT:
tags: {tags}
summary: {summary}

EXAMPLES:
- artificial_intelligence -> artificial intelligence [underscore removed]
- cloud-computing -> cloud-computing [hyphen is valid, so tag remains unchanged]

Now produce the JSON output.
"""

        # Finalizer LLM chain
        finalizer_prompt = ChatPromptTemplate.from_template(finalizer_prompt_template)
        finalizer_llm_chain = finalizer_prompt | self.llm_finalizer
        finalizer_output = finalizer_llm_chain.invoke({"tags":tags, "summary":summary})

        # extracting JSON from output
        finalizer_response  = finalizer_output.content

        # Extracting JSON from string
        finalizer_response = json.loads(finalizer_response)

        return finalizer_response
    

# Test data
blog_title  ="""Why Reading Still Matters in the Digital Age"""
blog_content = """Despite the rise of short-form content and social media, reading remains a powerful habit. Books encourage deep thinking, improve vocabulary, and strengthen concentration. Unlike quick online scrolling, reading allows ideas to unfold gradually, helping readers develop patience and critical thinking. Whether fiction or non-fiction, reading exposes us to new perspectives and experiences, making it a timeless tool for personal growth."""

# blog_title = "Why Python Remains the Go-To Language for Data Science"

# blog_content = """
# Python continues to dominate the data science ecosystem, and for good reason. Its simple, readable syntax lowers the barrier to entry, allowing analysts and engineers to focus more on solving problems than wrestling with code. A rich ecosystem of libraries—such as NumPy, Pandas, Matplotlib, and Scikit-learn—covers the entire data workflow, from data cleaning to model deployment.

# Beyond libraries, Python integrates seamlessly with big data tools, cloud platforms, and production systems, making it suitable for both experimentation and real-world applications. Strong community support ensures continuous improvement, extensive documentation, and rapid troubleshooting.

# Whether you’re building dashboards, training machine learning models, or automating data pipelines, Python offers the flexibility and scalability needed to turn data into actionable insights.


# # """
# Creating object of SummaryTagsAgent
agent = SummaryTagsAgent(blog_title, blog_content)
# Running planner agent
tags, summary =agent.plannerAgent()
print("Planner Agent Output: \n")
print("Tags: ",tags)
print(f"Number of tags: {len(tags)}\n")
print("Summary: ", summary)
print(f"Number of words: {len(summary.split(" "))}\n")
print("--------------------------------------------------\n")

# Running reviewer agent
updated_tags, updated_summary = agent.reviewerAgent(tags, summary)
print("Reviewer Agent Output: \n")
print("Updated tags: ", updated_tags)
print(f"Number of tags: {len(updated_tags)}\n")
print("Updated summary: ", updated_summary)
print(f"Number of words: {len(updated_summary.split(" "))}\n")

# Finalizer output
final_output = agent.finalizer(updated_tags, updated_summary)
print("--------------------------------------------------\n")
print("Final Output: \n")
print(final_output)